/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Task4_Main */

#ifndef _Included_Task4_Main
#define _Included_Task4_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Task4_Main
 * Method:    memoryOverflow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Task4_Main_memoryOverflow
  (JNIEnv *, jclass);

/*
 * Class:     Task4_Main
 * Method:    error
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Task4_Main_error
  (JNIEnv *, jclass);

/*
 * Class:     Task4_Main
 * Method:    getStringLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Task4_Main_getStringLength
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Task4_Main
 * Method:    printPersonInfo
 * Signature: (LTask4/Person;)V
 */
JNIEXPORT void JNICALL Java_Task4_Main_printPersonInfo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Task4_Main
 * Method:    changePersonAge
 * Signature: (LTask4/Person;)V
 */
JNIEXPORT void JNICALL Java_Task4_Main_changePersonAge
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Task4_Main
 * Method:    getStructPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Task4_Main_getStructPointer
  (JNIEnv *, jclass);

/*
 * Class:     Task4_Main
 * Method:    printStructByPointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Task4_Main_printStructByPointer
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
